version: '3.6'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  app:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - SERVER_PORT=8080
      - MAILGUN_DOMAIN=<ADD_MAILGUN_DOMAIN>
      - MAILGUN_API_KEY=<ADD_MAILGUN_API_KEY>
      - TWILIO_DOMAIN=<ADD_TWILIO_DOMAIN>
      - TWILIO_API_KEY=<ADD_TWILIO_API_KEY>
      - SLACK_API_KEY=<ADD_SLACK_API_KEY>
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8080:8080"
    depends_on:
      - redis